kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/app
  uid: 483e7e0a-dc48-4e3a-a964-aacf5998e8da
  resourceVersion: '63253'
  generation: 2
  creationTimestamp: '2020-03-08T09:29:08Z'
  labels:
    io.kompose.service: app
  annotations:
    deployment.kubernetes.io/revision: '2'
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.21.0
      (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"app"},"name":"app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"app"}},"strategy":{},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.21.0
      (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"app"}},"spec":{"containers":[{"image":"app","imagePullPolicy":"IfNotPresent","name":"app","ports":[{"containerPort":5002}],"resources":{}}],"restartPolicy":"Always","serviceAccountName":"","volumes":null}}},"status":{}}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
    spec:
      containers:
        - name: app
          image: app
          ports:
            - containerPort: 5002
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-03-08T16:24:59Z'
      lastTransitionTime: '2020-03-08T16:24:59Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-03-08T16:24:59Z'
      lastTransitionTime: '2020-03-08T16:24:57Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "app-c6c88c588" has successfully progressed.
