kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: default
  selfLink: /api/v1/namespaces/default/services/app
  uid: af13e053-b993-41cb-9009-df50063e905d
  resourceVersion: '67246'
  creationTimestamp: '2020-03-08T09:15:58Z'
  labels:
    io.kompose.service: app
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.21.0
      (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"app"},"name":"app","namespace":"default"},"spec":{"ports":[{"name":"5002","port":5002,"targetPort":5002}],"selector":{"io.kompose.service":"app"}},"status":{"loadBalancer":{}}}
spec:
  ports:
    - name: '5002'
      protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 31040
  selector:
    io.kompose.service: app
  clusterIP: 10.96.148.181
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
