kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: app-c6c88c588
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/replicasets/app-c6c88c588
  uid: fa30db9a-36ab-48a7-a384-8ae53f50f4a9
  resourceVersion: '63241'
  generation: 1
  creationTimestamp: '2020-03-08T16:24:57Z'
  labels:
    io.kompose.service: app
    pod-template-hash: c6c88c588
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '2'
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: app
      uid: 483e7e0a-dc48-4e3a-a964-aacf5998e8da
      controller: true
      blockOwnerDeletion: true
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
      pod-template-hash: c6c88c588
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
        pod-template-hash: c6c88c588
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
    spec:
      containers:
        - name: app
          image: app
          ports:
            - containerPort: 5002
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 1
