kind: Service
apiVersion: v1
metadata:
  name: db
  namespace: default
  selfLink: /api/v1/namespaces/default/services/db
  uid: a3469807-e9a8-418a-94f8-dc06ee358019
  resourceVersion: '234652'
  creationTimestamp: '2020-03-08T17:16:07Z'
  labels:
    io.kompose.service: db
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.21.0
      (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"db"},"name":"db","namespace":"default"},"spec":{"ports":[{"name":"32000","port":3306,"targetPort":3306}],"selector":{"io.kompose.service":"db"}},"status":{"loadBalancer":{}}}
spec:
  ports:
    - name: '32000'
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000
  selector:
    io.kompose.service: db
  clusterIP: 10.97.136.22
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
