kind: Service
apiVersion: v1
metadata:
  name: db
  namespace: default
  selfLink: /api/v1/namespaces/default/services/db
  uid: e90c62ee-f6a0-4443-8e1f-6b53a4b02216
  resourceVersion: '6087'
  creationTimestamp: '2020-03-08T09:16:06Z'
  labels:
    io.kompose.service: db
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.21.0
      (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"db"},"name":"db","namespace":"default"},"spec":{"ports":[{"name":"32000","port":32000,"targetPort":3306}],"selector":{"io.kompose.service":"db"}},"status":{"loadBalancer":{}}}
spec:
  ports:
    - name: '32000'
      protocol: TCP
      port: 32000
      targetPort: 3306
  selector:
    io.kompose.service: db
  clusterIP: 10.109.208.249
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
